### ISSUE TITLE
I used XsReader to get seeds by catch npc(10M gay) blinks before get Piplup，but always failure

### ISSUE THREAD

**Issue by longzhongba** [niart120/Project_eXcelSior#1]
I used XsReader to get  seeds catch heroine blinks on win11,and it works.
Then I restart the game to get gift Piplup(by the lake)，I can't let heroine standstill by using important item(like fishing rod),so I try to catch npc(10M  gay) blinks. He will standstill after doctor leave the lake becasuse of the conversation.
But I tried at least 10 times to get seeds, it always failure.
XsReader can't get seeds by catch npc(10M  gay or other npcs) blinks?

**Comment by niart120** [comment]
(using DeepL)
Thank you for your report.

Unfortunately, the tool does not currently implement the feature of getting Seeds in an environment with NPCs .
I am planning to support this feature in the future, but the timing is not yet determined.

Sorry for the inconvenience.

(Original text)
報告ありがとうございます。

残念ながら、現在このツールではNPCが存在する環境でのSeed取得の機能を実装していません。
今後対応予定ではありますが、時期は未定です。

お力添えできず申し訳ございません。

**Comment by longzhongba** [comment]
ok，ty for the reply



---Original---
From: ***@***.***&gt;
Date: Thu, Aug 17, 2023 23:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [niart120/Project_eXcelSior] I used XsReader to get seeds bycatch npc(10M gay) blinks before get Piplup，but




 
(using DeepL)
 Thank you for your report.
 
Unfortunately, the tool does not currently implement the ability to acquire Seeds in an environment with NPCs .
 I am planning to support this feature in the future, but the timing is not yet determined.
 
Sorry for the inconvenience.
 
(Original text)
 報告ありがとうございます。
 
残念ながら、現在このツールではNPCが存在する環境でのSeed取得の機能を実装していません。
 今後対応予定ではありますが、時期は未定です。
 
お力添えできず申し訳ございません。

**Comment by longzhongba** [comment]
邮件已收到
